### ISSUE TITLE
Handle type === 'embed'

### ISSUE THREAD

**Issue by ssgriffen** [tornqvist/prismic-element#2]
It'd be great if you could just grab the oembed.html and tack it on to the html array you pass back somehow

**Comment by tornqvist** [comment]
I'm not sure I understand what you mean. It does inject the raw html in a div, just like how [prismic-dom](https://github.com/prismicio/prismic-dom) does it (see https://github.com/tornqvist/prismic-element/blob/master/index.js#L52)

If you want to get at the raw html yourself I recommend you supply a custom serializer, as per the docs: https://prismic.io/docs/javascript/query-the-api/html-serializer

```javascript
var html = require('bel')
var raw = require('bel/raw')
var asElement = require('prismic-element')
var Elements = require('prismic-richtext').Elements

asElement(doc.data.body, linkResolver, function (element, content, children) {
  switch (element.type) {
    case Elements.embed: return html`
      <div class="my-custom-embed embed-type-${element.provider_name}">
        ${raw(element.oembed.html)}
      </div>
    `
    default: return null
  }
})
```

I guess this probably should be in the readme though…

**Comment by ssgriffen** [comment]
lol. I'm an idiot. Thanks for the quick reply disregard my msg..

**Comment by tornqvist** [comment]
You're most absolutely not. Happy coding!
